# Generated by Django 5.0.2 on 2024-05-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='current_layout',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
