# Generated by Django 5.0.2 on 2024-03-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurantlayout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlayout',
            old_name='layout',
            new_name='position',
        ),
    ]
