# Generated by Django 5.0.2 on 2024-04-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_waitlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlayout',
            old_name='position',
            new_name='layout',
        ),
    ]
