# Generated by Django 5.0.2 on 2024-04-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_position_restaurantlayout_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlayout',
            name='name',
            field=models.CharField(default={'name': 'filler name'}, max_length=50),
            preserve_default=False,
        ),
    ]
